import Tech from "./resources/tech.jpg";
import Background from "./resources/background.jpg";
import Monitoreo1 from "./resources/capturas/monitoreo.PNG";
import Monitoreo2 from "./resources/capturas/monitoreo2.PNG";
import Monitoreo3 from "./resources/capturas/monitoreo3.PNG";
import Monitoreo4 from "./resources/capturas/monitoreo4.PNG";
import IvaloWA1 from "./resources/capturas/ivaloWA1.PNG";
import IvaloWA2 from "./resources/capturas/ivaloWA2.PNG";
import IvaloWA3 from "./resources/capturas/ivaloWA3.PNG";
import IvaloWA4 from "./resources/capturas/ivaloWA4.PNG";
import IvaloMA1 from "./resources/capturas/ivaloMA1.jpg";
import IvaloMA2 from "./resources/capturas/ivaloMA2.jpg";
import Seguridad1 from "./resources/capturas/seguridad.jpg";
import Seguridad2 from "./resources/capturas/seguridad2.jpg";
import Seguridad3 from "./resources/capturas/seguridad3.jpg";
import Seguridad4 from "./resources/capturas/seguridad4.jpg";
import LogoRedux from "./resources/logos/redux.png";
import LogoReact from "./resources/logos/react.png";
import LogoNode from "./resources/logos/node.png";
import LogoJavascript from "./resources/logos/javascript.png";
import LogoHtml from "./resources/logos/html.png";
import LogoCss from "./resources/logos/css.png";
import LogoGithub from "./resources/logos/github.png";
import LogoLinkedin from "./resources/logos/linkedin.png";
import LogoMySQL from "./resources/logos/mysql.png";
import LogoTypescript from "./resources/logos/typescript.png";
const images =  {Tech, Background, Seguridad1, Seguridad2, Seguridad3, Seguridad4, Monitoreo1, Monitoreo2, Monitoreo3, Monitoreo4, LogoCss, LogoHtml, LogoJavascript, LogoNode, LogoReact, LogoRedux, LogoGithub, LogoLinkedin, LogoMySQL, LogoTypescript, IvaloWA1, IvaloWA2, IvaloWA3, IvaloWA4, IvaloMA1, IvaloMA2};
export default images
